version: "3"

services:
  soft_serve:
    image: soft-serve
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: ${WORKDIR:-/data}
    ports:
      - "${HOST_BIND_ADDRESS}:${HOST_PORT}:${SOFT_SERVE_PORT}"
    volumes:
      - ${HOST_DATA_DIR:-.}/data:${WORKDIR:-/data}
      - ${HOST_SOFT_DIR:-.}/soft:/usr/local/bin/soft
    env_file: .env
    restart: always
    command: /usr/local/bin/soft serve
